include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"
  errors:
    invalid_annotation_target: ignore
    avoid_print: error
    missing_return: error
    dead_code: info
    cancel_subscriptions: warning
    avoid_dynamic_calls: warning

linter:
  rules:
    - avoid_print
    - always_declare_return_types
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - avoid_relative_lib_imports
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - cancel_subscriptions
    - empty_statements
    - no_duplicate_case_values
    - prefer_void_to_null
    - prefer_single_quotes
    - unrelated_type_equality_checks
    - prefer_relative_imports
