name: news_app
description: "Technical test"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.5
  internet_connection_checker_plus: ^2.3.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  bloc: ^8.1.4
  dio: ^5.4.2
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  mockito: ^5.4.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env

flutter_gen:
  output: lib/core/gen
  line_length: 80
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
